# Generated by Django 3.0.4 on 2024-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_fornecedor_arquivo_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='arquivo_medicamento',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='arquivo_medicamentos',
            field=models.FileField(blank=True, help_text='Arquivos extenção .csv', null=True, upload_to='midias', verbose_name='Relação medicamentos'),
        ),
    ]
