# Generated by Django 5.0.5 on 2024-05-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, choices=[('HUMANAS', 'Ciências Humanas'), ('SAUDE', 'Ciências da Saúde'), ('SOCIAIS', 'Ciências Sociais'), ('TECNOLOGICAS', 'Ciências Tecnológicas')], help_text='* Escolha área de interesse de trabalho', max_length=12, null=True, verbose_name='Área de pesquisa *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulacao',
            field=models.CharField(blank=True, choices=[('TECNICO', 'Técnico'), ('GRADUANDO', 'Graduando'), ('GRADUADO', 'Graduado'), ('ESPECIALISTA', 'Especialista'), ('MESTRE', 'Mestre'), ('DOUTOR', 'Doutor')], default='MEMBRO', help_text='* Campos obrigatórios', max_length=15, null=True, verbose_name='Titulação'),
        ),
    ]
